version: '3.8'

services:
  flask_app_devops:
    container_name: flask_app_container
    image: francescoxx/flask_live_app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:khaliladmin@devops_bd:5432/postgres
    depends_on:
      - devops_bd

  devops_bd:
    container_name: devops_bd
    image: postgres:12
    ports:
      - "5450:5432"
    environment:
      POSTGRES_PASSWORD: khaliladmin
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  sonar_db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  pgdata: {}
  sonar_db_data: {}
  sonarqube_conf: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_logs: {}
  sonarqube_temp: {}
