"""empty message

Revision ID: ca0c8d80a764
Revises: 90e5b600e8b2
Create Date: 2024-07-12 17:46:09.679766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0c8d80a764'
down_revision = '90e5b600e8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1200),
               existing_nullable=False)
        batch_op.alter_column('phonenumber',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=15000),
               existing_nullable=False)
        batch_op.alter_column('confirmpassword',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=15000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirmpassword',
               existing_type=sa.String(length=15000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=15000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('phonenumber',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
